### ISSUE TITLE
Bug in display settings

### ISSUE THREAD

**Issue by mfvp** [dliaomcp/fbstab#8]
Compilation error on Windows

error C2061: syntax error: identifier 'Display'
In fbstab_algorithm.h, line 274:
FBstabAlgorithm::Display display_level_ = Display::FINAL;

The problem was fixed after replacing this line by:

Display display_level_ = Display::FINAL;

**Comment by dliaomcp** [comment]
I've made some updates that should fix the issue, can you give it a try when you get the chance and if it works I'll close it? (I haven't had time to set up CI yet so I can't run the windows tests myself ATM)

**Comment by mfvp** [comment]
Compilation on windows is failing. Please see attachment
[win_error.txt](https://github.com/dliaomcp/fbstab/files/4531191/win_error.txt)

**Comment by dliaomcp** [comment]
OK I think this should fix it,
Try inlining those definitions, i.e., at line 624:

inline void AlgorithmParameters::ValidateOptions() {
  sigma0 = std::max(sigma0, 1e-10);

}
and so on for the others two as well

inline void AlgorithmParameters::DefaultParameters()
inline void AlgorithmParameters::ReliableParameters()

**Comment by mfvp** [comment]
The inlining solves some of the problems. However, the following linker errors still persist: 
[win_error2.txt](https://github.com/dliaomcp/fbstab/files/4531964/win_error2.txt)

To answer your previous question, I built the project using the cmake GUI with BUILD_GMOCK and INSTALL_GTEST checked, and then compiled the code in release mode using visual studio

**Comment by dliaomcp** [comment]
Hmm ok I'm not sure what this is then, I'm not able to reproduce it.
This is suggesting you try a clean build (if you haven't already) https://docs.microsoft.com/en-us/previous-versions/jj889284(v=vs.140)?redirectedfrom=MSDN

Since you're building using VS it could also be something like this:
https://stackoverflow.com/questions/28887001/lnk2038-mismatch-detected-for-runtimelibrary-value-mt-staticrelease-doesn

Whats does release mode in VS do? Also, where are the BUILD_GMOCK and INSTALL_GTEST options coming in? (I've never used the GUI, I've been working entirely in the command line)

**Comment by mfvp** [comment]
The fix in [this comment](https://stackoverflow.com/a/61380606) solved the problem. In Visual Studio, I had to change the configuration type of mpc_unit_tests and dense_unit_tests to Static Library. I did this for both release and debug modes. I wonder if such change will cause other issues.
I didn't have these linker problem before your latest commits. In fact, the only problem that I had in the past was in the display settings, which was easily fixed as I described in the initial comment of this thread.

In Visual studio, debug mode includes debug information in the compiled files (allowing easy debugging) while release mode has optimizations enabled.
Regarding BUILD_GMOCK and INSTALL_GTEST, they automatic appear in the cmake GUI when building the project. 
![cmake](https://user-images.githubusercontent.com/40307367/80317264-bd791d80-87d0-11ea-96a3-730f5e9eb869.JPG)

**Comment by dliaomcp** [comment]
OK thats as expected, the build system is configured to use static libraries so using dynamic libraries instead could definitely cause an issue.

Thats strange since those issues are independent from the changes I made, there shouldn't be any relation. The errors (after the first round of fixes ofc) are actually all in the gtest module so I suspect your settings were somehow incompatible with gtest?
